apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "{{ .Values.service.name }}-vs"
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "{{ .Values.ingress.host }}"
  gateways:
    - msa-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: "{{ .Values.service.name }}.{{ .Values.service.namespace }}.svc.cluster.local"
            port:
              number: {{ .Values.service.port }}