apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://gitea.dev-tools.svc.cluster.local:3000/admin/manifest-repo.git'
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://gitea.dev-tools.svc.cluster.local:3000/admin/manifest-repo.git'
    targetRevision: main
    path: backend-app/k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-backend
  syncPolicy:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://gitea.dev-tools.svc.cluster.local:3000/dev/manifest-repo.git'
    targetRevision: main
    path: istio-config
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
